#!/usr/bin/env python3
"""
Bundle JanusDBG SageLang modules into a single .sage file for compilation.

Resolves local imports (from lib.*, from src.*) and inlines them
in dependency order. Standard library imports are deduplicated
and emitted once at the top.

Usage:
    python3 tools/bundle.py [entry.sage] [output.sage]
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src"
LIB = ROOT / "lib"
BUILD = ROOT / "build"
LOCAL_PREFIXES = ("lib.", "src.")

def find_all_imports(content: str) -> tuple[list[str], list[str]]:
    """Return (local_imports, stdlib_imports) found in content."""
    local_imports = []
    stdlib_imports = []
    for line in content.splitlines():
        m = re.match(r"^\s*from\s+([a-z.]+)\s+import", line)
        if m:
            module = m.group(1)
            if any(module.startswith(p) for p in LOCAL_PREFIXES):
                local_imports.append(module)
            else:
                stdlib_imports.append(line.strip())
            continue
        m = re.match(r"^\s*import\s+([a-z.]+)", line)
        if m:
            module = m.group(1)
            if any(module.startswith(p) for p in LOCAL_PREFIXES):
                local_imports.append(module)
            else:
                stdlib_imports.append(line.strip())
    return local_imports, stdlib_imports

def module_to_path(dotted: str) -> Path:
    parts = dotted.split(".")
    if parts[0] == "lib":
        return LIB / f"{parts[1]}.sage"
    elif parts[0] == "src":
        path = SRC
        for p in parts[1:]:
            path = path / p
        if path.with_suffix(".sage").exists():
            return path.with_suffix(".sage")
        return path / "__init__.sage"
    raise ValueError(f"Unknown module prefix: {dotted}")

def resolve_dependency_order(entry: Path) -> list[Path]:
    visited = set()
    order = []

    def visit(path: Path):
        resolved = path.resolve()
        if resolved in visited:
            return
        visited.add(resolved)
        local_imports, _ = find_all_imports(resolved.read_text())
        for dep_dotted in local_imports:
            try:
                dep_path = module_to_path(dep_dotted)
                visit(dep_path)
            except ValueError:
                pass
        order.append(resolved)

    visit(entry.resolve())
    return order

def strip_all_imports(content: str) -> str:
    """Remove ALL import lines - stdlib goes to header, local gets inlined."""
    lines = []
    for line in content.splitlines(keepends=True):
        if re.match(r"^\s*(from\s+|import\s+)", line):
            continue
        lines.append(line)
    return "".join(lines)

def bundle(entry: str = "src/main.sage", output: str | None = None) -> str:
    entry_path = ROOT / entry
    if not entry_path.exists():
        print(f"Error: entry file not found: {entry_path}", file=sys.stderr)
        sys.exit(1)

    files = resolve_dependency_order(entry_path)
    output_path = (BUILD / (output or "janusdbg_bundle.sage")).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Collect all stdlib imports across all files (deduplicated, preserving order)
    seen_stdlib = set()
    stdlib_header = []
    for f in files:
        _, stdlib_imports = find_all_imports(f.read_text())
        for imp in stdlib_imports:
            if imp not in seen_stdlib:
                seen_stdlib.add(imp)
                stdlib_header.append(imp)

    lines = []
    lines.append("## JanusDBG — bundled single-file build\n")
    lines.append("## Generated by tools/bundle.py — do not edit directly\n")
    lines.append("\n## -- stdlib imports --\n")
    for imp in stdlib_header:
        lines.append(imp + "\n")
    lines.append("")

    for f in files:
        rel = f.relative_to(ROOT)
        content = f.read_text()
        content = strip_all_imports(content)
        lines.append(f"\n## --- {rel} ---\n")
        lines.append(content)
        if not content.endswith("\n"):
            lines.append("\n")

    result = "".join(lines)
    output_path.write_text(result)
    return str(output_path)


if __name__ == "__main__":
    entry = sys.argv[1] if len(sys.argv) > 1 else "src/main.sage"
    out = sys.argv[2] if len(sys.argv) > 2 else None
    path = bundle(entry, out)
    print(f"Bundled: {path}")
