#!/usr/bin/env python3
"""
Generate a self-contained JIT-launched shell script for JanusDBG.

Bundles all SageLang modules into a single file and wraps it in
an executable shell script that launches via:

    sage --jit <bundle>

This replaces the old C-stub launcher: native module calls (tcp, etc.)
work correctly under --jit, and the resulting "binary" is a portable
shell script requiring only bash and the sage interpreter.
"""

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SAGE = ROOT / "deps" / "SageLang" / "sage"
BUILD = ROOT / "build"
BINARY_NAME = "janusdbgd"

LAUNCHER_TEMPLATE = r"""#!/usr/bin/env bash
# JanusDBG — JIT-launched debugger backend
# Generated by tools/deploy.py — do not edit directly
set -e
TMPFILE=$(mktemp /tmp/janusdbg_XXXXXX.sage)
trap "rm -f '$TMPFILE'" EXIT
cat > "$TMPFILE" << 'JANUSDBG_EOF'
%s
JANUSDBG_EOF
exec sage --jit "$TMPFILE" "$@"
"""


def bundle_script() -> str:
    """Run bundle.py and return the bundled source."""
    bundle_py = ROOT / "tools" / "bundle.py"
    result = subprocess.run(
        [sys.executable, str(bundle_py)],
        capture_output=True, text=True, cwd=ROOT,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    bundle_path = (BUILD / "janusdbg_bundle.sage").resolve()
    if not bundle_path.exists():
        print("Error: bundle was not created", file=sys.stderr)
        sys.exit(1)
    content = bundle_path.read_text()
    return content


def build_launcher(target: str = "native") -> str:
    """Build a self-contained JIT launcher script for the given target.

    The target name is only used for the output filename; the launcher
    is identical across all targets (it runs via 'sage --jit' which is
    architecture-independent).
    """
    BUILD.mkdir(parents=True, exist_ok=True)

    print(f"  Bundling source modules...")
    bundled = bundle_script()

    out_path = BUILD / f"{BINARY_NAME}_{target}"
    launcher = LAUNCHER_TEMPLATE % bundled
    out_path.write_text(launcher)
    out_path.chmod(0o755)

    print(f"  Output: {out_path}")
    return str(out_path)


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "native"
    build_launcher(target)
